package pi;

import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URI;
import java.net.URL;
import java.sql.PreparedStatement;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot3D;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.util.Rotation;

public class Menu extends javax.swing.JFrame {

    public Menu() {
        
        
        initComponents();
          // essa parte seta a tela principal para maximinizado
        this.setExtendedState(this.getExtendedState()|JFrame.MAXIMIZED_BOTH); 
        URL url = this.getClass().getResource("/Imagens/dolar.gif");  
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);  
        this.setIconImage(imagemTitulo);
        this.setTitle("Bem-vindo ao SoftMoney");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblsaldo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setText("Novo lembrete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 230, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Cálculo Final");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 230, 40));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setText("Nova Receita");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 230, 40));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setText("Gráfico comparativo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 230, 40));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("Nova Despesa");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 230, 40));

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setText("Usuario");
        Sessao sessao = Sessao.getInstancia();
        lblUsuario.setText("Bem-Vindo: "+sessao.getLoginUsuario());
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 350, 30));

        lblsaldo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblsaldo.setForeground(new java.awt.Color(255, 255, 255));
        lblsaldo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsaldo.setText("Saldo Atual");
        NumberFormat formatter = new DecimalFormat("¤ #,##0.00");
        SomaTotal soma = new SomaTotal();
        int id = sessao.getIdUsuario();
        lblsaldo.setText("Saldo Atual: "+formatter.format(soma.SomaReceitas(id) - soma.SomaDespesas(id)));
        getContentPane().add(lblsaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, 350, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Background2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -210, 1750, 1180));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, -1, -1));

        jToggleButton1.setText("jToggleButton1");
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, -1, -1));

        jMenu6.setText("Editar dados");
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setText("Editar Receita");
        jMenuItem14.setActionCommand("");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem14);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem15.setText("Editar Despesa");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem15);

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem16.setText("Editar Lembrete");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem16);

        jMenuBar1.add(jMenu6);

        jMenu5.setText("Perfil");

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setText("Editar");
        jMenuItem11.setActionCommand("");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem11);

        jMenuBar1.add(jMenu5);

        jMenu2.setText("Sistema");

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Logoff");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Fechar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("  Ajuda   ");

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Manual");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem10.setText("Sobre");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setText("Facebook");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem12);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 1310, 778);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//            Lembrete cadastrLembrete = new Lembrete();
//            cadastrLembrete.show();
        Lembrete teste = new Lembrete();
        teste.show();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        CalculoTotal calculo = new CalculoTotal();
        calculo.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Receitas novaReceita = new Receitas(this);
        novaReceita.show();        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
     //gráfico
      
     /**
     * 
     * Conecção
     * 
     */
    
        
        Conexao carregaGrafico = new Conexao();
        carregaGrafico.abrirConexao();
        carregaGrafico.rs = null;
        double valorReceitaTotal = 0;
        double valorDespesaTotal = 0;
        double resultadoEconomia = 0;
        Sessao sessao = Sessao.getInstancia();
        int id = sessao.getIdUsuario();
        try {
            carregaGrafico.st = carregaGrafico.con.createStatement();
            PreparedStatement st = carregaGrafico.con.prepareStatement("SELECT valor FROM receitas WHERE ID_usuario = ?");
            st.setInt(1, id);
            
            
            carregaGrafico.rs = st.executeQuery();
           
           while(carregaGrafico.rs.next()){
               
                valorReceitaTotal = valorReceitaTotal + carregaGrafico.rs.getDouble("valor");
            }
            
            
        } catch (Exception e) {
        }
        
        try {
            carregaGrafico.st = carregaGrafico.con.createStatement();
            PreparedStatement st = carregaGrafico.con.prepareStatement("SELECT valor FROM despesas WHERE ID_usuario = ?");
            st.setInt(1, id);
            
            
            carregaGrafico.rs = st.executeQuery();
           
           while(carregaGrafico.rs.next()){
               
                valorDespesaTotal = valorDespesaTotal + carregaGrafico.rs.getDouble("valor");
            }
            
            
        } catch (Exception e) {
        }
        
        resultadoEconomia = valorReceitaTotal - valorDespesaTotal;
        
                if((valorReceitaTotal==0 )&&(valorDespesaTotal==0)){
           JOptionPane.showMessageDialog(null,"Atenção! "+"\n Você não possui dados cadastrados no sistema");  
        }
		
		else if((valorReceitaTotal ==0)&&(valorDespesaTotal >0)){
            JOptionPane.showMessageDialog(null,"Atenção!"+"\n Você deve poupar mais, você possui somente despesas"+"\nAcesse nosso site para dicas financeiras" );   
        }    
            

		else if(resultadoEconomia<0){
           JOptionPane.showMessageDialog(null,"Devagar! "+"\nVocê gastou todo sua receita"+"\nAcesse nosso site para dicas financeiras");
        }
		
		else if(valorReceitaTotal > valorDespesaTotal ){
            JOptionPane.showMessageDialog(null," Sempre no azul! "+"\n Parabéns você conseguiu economizar ... ");
        }
		          
        
        
        if((valorReceitaTotal>0)&&(valorDespesaTotal==0)){
        
        JOptionPane.showMessageDialog(null," ENTRO NO IF");
        
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        
        pieDataset.setValue("Despesas", new Double(0));
        pieDataset.setValue("Receitas", new Double(valorReceitaTotal));
        pieDataset.setValue("Economia", new Double(0));
 
        JFreeChart chart = ChartFactory.createPieChart3D("Gráfico Demostrativo", pieDataset, true, false, true);
        
        PiePlot3D plot = (PiePlot3D) chart.getPlot();
        plot.setStartAngle(290);
        plot.setDirection(Rotation.CLOCKWISE);
        plot.setForegroundAlpha(0.5f);
        plot.setNoDataMessage("Favor incluir dados no sistema!");
       
        ChartFrame frame = new ChartFrame("Gráfico", chart);
        frame.setVisible(true);
        frame.setLocation(380, 150);
        frame.setSize(600, 500);
 
            
	}else{
            
        DefaultPieDataset pieDataset = new DefaultPieDataset();
        pieDataset.setValue("Despesas", new Double(valorDespesaTotal));
        pieDataset.setValue("Receitas", new Double(valorReceitaTotal));
        pieDataset.setValue("Economia", new Double(resultadoEconomia));
            

        JFreeChart chart = ChartFactory.createPieChart3D("Gráfico Demostrativo", pieDataset, true, false, true);
        
        PiePlot3D plot = (PiePlot3D) chart.getPlot();
        plot.setStartAngle(290);
        plot.setDirection(Rotation.CLOCKWISE);
        plot.setForegroundAlpha(0.5f);
        plot.setNoDataMessage("Favor incluir dados no sistema!");
       
        ChartFrame frame = new ChartFrame("Gráfico", chart);
        frame.setVisible(true);
        frame.setLocation(380, 150);
        frame.setSize(600, 500);
        
        }
        
   // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        direitosReservados sobre = new direitosReservados();
        sobre.show();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       System.exit(WIDTH);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        Sessao.getInstancia().finalizar();
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        EditarPerfil editarPerfil = new EditarPerfil(this);
        editarPerfil.show();
        
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed

        TabelaReceitas tabela = new TabelaReceitas(this);
        tabela.show();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        
        TabelaDespesas tabela = new TabelaDespesas(this);
        tabela.show();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
           try{
               URI linkFacebook = new URI("https://www.facebook.com/SoftMoney2015?fref=ts");
               Desktop.getDesktop().browse(linkFacebook);
           }catch(Exception erro){
               System.out.println(erro);
               
           }
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        TabelaLembretes tabela = new TabelaLembretes();
        tabela.show();
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed

    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Despesas novaDespesa = new Despesas(this);
        novaDespesa.show();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }
    
    public void atualizarUsuarioLogado() {
        Sessao sessao = Sessao.getInstancia();
        lblUsuario.setText("Bem-Vindo: "+sessao.getLoginUsuario());
    }
    public void atualizarSaldoAtual(){
        Sessao sessao = Sessao.getInstancia();
        NumberFormat formatter = new DecimalFormat("¤ #,##0.00");
        int id = sessao.getIdUsuario();
        SomaTotal soma = new SomaTotal();
        double valor = soma.SomaReceitas(id) - soma.SomaDespesas(id);
        lblsaldo.setText("Saldo Atual: "+formatter.format(valor));
    }
            

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblsaldo;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
